name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DB_NAME: notes
      DB_HOST: localhost
      DB_ROOT_USER: root
      DB_ROOT_PASS: root
      DB_TEST_USER: test
      DB_TEST_PASS: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up MySQL
      run: |
        sudo systemctl start mysql
        mysql -h ${{env.DB_HOST}} -u ${{env.DB_ROOT_USER}} -p${{env.DB_ROOT_PASS}} < sql/notes.sql
        mysql -u ${{env.DB_ROOT_USER}} -p${{env.DB_ROOT_PASS}} -e 'CREATE USER ${{env.DB_TEST_USER}}@${{env.DB_HOST}} IDENTIFIED BY "${{env.DB_TEST_PASS}}";
                                                                   GRANT ALL PRIVILEGES ON ${{env.DB_NAME}}.* TO ${{env.DB_TEST_USER}}@${{env.DB_HOST}};'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Test with Maven
      run: mvn clean test --batch-mode --file pom.xml
